baseURL = 'http://githegipen.dev'
languageCode = 'en-gb'
theme = 'hugo-tufte'
title = "Githegi's Pen"

[params]
subtitle = "Essays about things that interest me"
github = "bikeboi"

# --
# Navigation
# --
[[menu.nav]]
me = "Home"
pre = "<i class='fas fa-home la-lg'></i>"
weight = -110
identifier = "home"
url = "/"

[[menu.nav]]
me = "Posts"
pre = "<i class='fas fa-book la-lg'></i>"
weight = -100
identifier = "posts"
url = "/post"

# --
# Footer
# --
[[menu.footer]]
  name = ""
  pre = "<i class='fab fa-linkedin fa-lg'></i> "
  weight = -90
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/michael-githegi-kareithi/"
